### ISSUE TITLE
Kernel

### ISSUE THREAD

**Issue by ghost** [AOSiP-Devices/kernel_oneplus_sdm845#10]
Ok

**Comment by ghost** [comment]
Swis

**Comment by anirudhgupta109** [comment]
what

**Comment by ghost** [comment]
friend I'm trying to build an Ancient build with tutorial here Github how
do I add the kernel on Github I'm new to that

Em qui, 23 de abr de 2020 17:58, anirudhgupta109 <notifications@github.com>
escreveu:
